import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-zinc-300"}>
        <Navbar />
        <section className="mx-[120px] bg-white h-[calc(100vh-132px)] shadow-2xl">
          {children}
        </section>
      </body>
    </html>
  );
}
