import "./globals.css";
import Navbar from "./components/Navbar";
import { Poppins } from "next/font/google";

const openSans = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className + " bg-[#d9d9d9]"}>
        <Navbar />
        <div className="mx-[120px] bg-white h-[calc(100vh-120px)] overflow-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
